name: pr-build-image

on:
  pull_request:
    branches: main
    
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/netshoot:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
